name: Deploy to GitHub Pages

on: [push]
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.12.0  # Updated to match the version in package.json
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install  # 使用pnpm进行依赖安装

      - name: Build
        run: pnpm build  # 使用pnpm进行构建
        env:
          GITHUB_PAGES: 'true'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # 要部署的文件夹，通常是构建输出目录